// Regiones y distritos de Lima
const MAPA_REGIONES = {
  "Lima Norte": ["Ancon","Carabayllo","Comas","Independencia","Los Olivos","Puente Piedra","San Martin de Porres","Santa Rosa"],
  "Lima Sur": ["Barranco","Chorrillos","Lurin","Pachacamac","Pucusana","Punta Hermosa","Punta Negra","San Bartolo","Santa Maria del Mar","Villa El Salvador","Villa Maria del Triunfo"],
  "Lima Este": ["Ate","Chaclacayo","Cieneguilla","El Agustino","La Molina","San Juan de Lurigancho","San Luis","Santa Anita"],
  "Lima Oeste": ["Brena","Jesus Maria","La Victoria","Lince","Magdalena del Mar","Miraflores","Pueblo Libre","San Isidro","San Miguel"],
  "Lima Centro": ["Cercado de Lima","Rimac","La Victoria","San Luis","Brena","Jesus Maria","Lince"]
};

// Datos separados por tipo de senalizacion y su icono por defecto
const senalesHorizontal = [
    {
        "id":  1,
        "tipo":  "Linea continua",
        "nombre":  "Linea guia",
        "estado":  "nueva",
        "region":  "Lima Este",
        "zona":  "Ate",
        "precio":  4200,
        "lat":  -12.05,
        "lng":  -77.03,
        "icono":  "pista",
        "fecha_colocacion":  "2024-10-12",
        "distrito":  "Ate"
    },
    {
        "id":  2,
        "tipo":  "Paso peatonal",
        "nombre":  "Cruce seguro",
        "estado":  "antigua",
        "region":  "Lima Norte",
        "zona":  "Los Olivos",
        "precio":  4550,
        "lat":  -12.048,
        "lng":  -77.045,
        "icono":  "paso",
        "fecha_colocacion":  "2024-09-03",
        "distrito":  "Los Olivos"
    },
    {
        "id":  3,
        "tipo":  "Flecha direccional",
        "nombre":  "Direccion obligatoria",
        "estado":  "sin_senal",
        "region":  "Lima Oeste",
        "zona":  "Miraflores",
        "precio":  4100,
        "lat":  -12.043,
        "lng":  -77.05,
        "icono":  "acceso",
        "fecha_colocacion":  "2024-08-21",
        "distrito":  "Miraflores"
    },
    {
        "id":  4,
        "tipo":  "Marca",
        "estado":  "antigua",
        "estado_fisico":  "deteriorada",
        "zona":  "Lince",
        "lat":  -12.086827984631269,
        "lng":  -77.03424721956254,
        "icono":  "flecha_arriba_der",
        "region":  "Lima Oeste",
        "nombre":  "Recto y derecha",
        "precio":  4250,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.9,
                            "largo":  2.8
                        },
        "area_m2":  2.52,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  "src/inspeccion/inspeccion-h-4.png",
        "distrito":  "Lince"
    },
    {
        "id":  5,
        "tipo":  "Marca",
        "estado":  "antigua",
        "estado_fisico":  "deteriorada",
        "zona":  "Lince",
        "lat":  -12.086906667065662,
        "lng":  -77.03420966863634,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.4,
                            "largo":  3
                        },
        "area_m2":  1.2000000000000002,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  6,
        "tipo":  "Marca",
        "estado":  "antigua",
        "estado_fisico":  "deteriorada",
        "zona":  "Lince",
        "lat":  -12.086953876515208,
        "lng":  -77.03419357538223,
        "icono":  "enrejado",
        "region":  "Lima Oeste",
        "nombre":  "Enrejado amarillo",
        "precio":  5700,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  3,
                            "largo":  4
                        },
        "area_m2":  12,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  "src/inspeccion/inspeccion-h-6.png",
        "distrito":  "Lince"
    },
    {
        "id":  7,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.087037804404936,
        "lng":  -77.0341855287552,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  3,
                            "largo":  0.4
                        },
        "area_m2":  1.2000000000000002,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  8,
        "tipo":  "Marca",
        "estado":  "antigua",
        "estado_fisico":  "deteriorada",
        "zona":  "Lince",
        "lat":  -12.08687257134694,
        "lng":  -77.03405678272249,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.4,
                            "largo":  3
                        },
        "area_m2":  1.2000000000000002,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  9,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.08702469067391,
        "lng":  -77.03403264284135,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  3,
                            "largo":  0.4
                        },
        "area_m2":  1.2000000000000002,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  10,
        "tipo":  "Marca",
        "estado":  "antigua",
        "estado_fisico":  "deteriorada",
        "zona":  "Lince",
        "lat":  -12.086953876515208,
        "lng":  -77.03404605388643,
        "icono":  "enrejado",
        "region":  "Lima Oeste",
        "nombre":  "Enrejado amarillo",
        "precio":  5700,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  3,
                            "largo":  4
                        },
        "area_m2":  12,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  11,
        "tipo":  "Marca",
        "estado":  "antigua",
        "estado_fisico":  "deteriorada",
        "zona":  "Lince",
        "lat":  -12.085755278467467,
        "lng":  -77.03415066003801,
        "icono":  "flecha_arriba_der",
        "region":  "Lima Oeste",
        "nombre":  "Recto y derecha",
        "precio":  4250,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.9,
                            "largo":  2.8
                        },
        "area_m2":  2.52,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  12,
        "tipo":  "Marca",
        "estado":  "sin_senal",
        "estado_fisico":  "no_operativa",
        "zona":  "Lince",
        "lat":  -12.085676595694483,
        "lng":  -77.03424721956254,
        "icono":  "flecha_arriba",
        "region":  "Lima Oeste",
        "nombre":  "Flecha recto",
        "precio":  4350,
        "fecha_colocacion":  "",
        "dimensiones":  {
                            "ancho":  0.66,
                            "largo":  2
                        },
        "area_m2":  1.32,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  13,
        "tipo":  "Marca",
        "estado":  "antigua",
        "estado_fisico":  "deteriorada",
        "zona":  "Lince",
        "lat":  -12.085702823288043,
        "lng":  -77.03438133001328,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  3,
                            "largo":  0.4
                        },
        "area_m2":  1.2000000000000002,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  14,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.0858077336366,
        "lng":  -77.03437060117722,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.4,
                            "largo":  3
                        },
        "area_m2":  1.2000000000000002,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  15,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.0857998653619,
        "lng":  -77.03420162200929,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.4,
                            "largo":  3
                        },
        "area_m2":  1.2000000000000002,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  16,
        "tipo":  "Marca",
        "estado":  "sin_senal",
        "estado_fisico":  "no_operativa",
        "zona":  "Lince",
        "lat":  -12.085671350175451,
        "lng":  -77.03419625759126,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "",
        "dimensiones":  {
                            "ancho":  0.4,
                            "largo":  3
                        },
        "area_m2":  1.2000000000000002,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  17,
        "tipo":  "Marca",
        "estado":  "antigua",
        "estado_fisico":  "deteriorada",
        "zona":  "Lince",
        "lat":  -12.086825361883054,
        "lng":  -77.03417748212816,
        "icono":  "flecha_arriba",
        "region":  "Lima Oeste",
        "nombre":  "Flecha recto",
        "precio":  4350,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.66,
                            "largo":  2
                        },
        "area_m2":  1.32,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  "src/inspeccion/inspeccion-h-17.png",
        "distrito":  "Lince"
    },
    {
        "id":  18,
        "tipo":  "Marca",
        "estado":  "antigua",
        "estado_fisico":  "deteriorada",
        "zona":  "Lince",
        "lat":  -12.085752655708733,
        "lng":  -77.03437060117722,
        "icono":  "enrejado",
        "region":  "Lima Oeste",
        "nombre":  "Enrejado amarillo",
        "precio":  5700,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  3,
                            "largo":  4
                        },
        "area_m2":  12,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  "src/inspeccion/inspeccion-h-18.png",
        "distrito":  "Lince"
    },
    {
        "id":  19,
        "tipo":  "Marca",
        "estado":  "sin_senal",
        "estado_fisico":  "no_operativa",
        "zona":  "Lince",
        "lat":  -12.085736919155847,
        "lng":  -77.03424453735353,
        "icono":  "enrejado",
        "region":  "Lima Oeste",
        "nombre":  "Enrejado amarillo",
        "precio":  5700,
        "fecha_colocacion":  "",
        "dimensiones":  {
                            "ancho":  3,
                            "largo":  4
                        },
        "area_m2":  12,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  20,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.087103373050471,
        "lng":  -77.03405141830446,
        "icono":  "flecha_arriba",
        "region":  "Lima Oeste",
        "nombre":  "Flecha recto",
        "precio":  4350,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.66,
                            "largo":  2
                        },
        "area_m2":  1.32,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  21,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.087098127559415,
        "lng":  -77.03398168087007,
        "icono":  "flecha_arriba_der",
        "region":  "Lima Oeste",
        "nombre":  "Recto y derecha",
        "precio":  4250,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.9,
                            "largo":  2.8
                        },
        "area_m2":  2.52,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  22,
        "tipo":  "Marca",
        "estado":  "sin_senal",
        "estado_fisico":  "no_operativa",
        "zona":  "Lince",
        "lat":  -12.08464060369242,
        "lng":  -77.03453958034517,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "",
        "dimensiones":  {
                            "ancho":  0.4,
                            "largo":  3
                        },
        "area_m2":  1.2000000000000002,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  23,
        "tipo":  "Marca",
        "estado":  "sin_senal",
        "estado_fisico":  "no_operativa",
        "zona":  "Lince",
        "lat":  -12.084611753224838,
        "lng":  -77.03437060117722,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "",
        "dimensiones":  {
                            "ancho":  0.4,
                            "largo":  6
                        },
        "area_m2":  2.4000000000000004,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  24,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.084742891688794,
        "lng":  -77.03452885150911,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.4,
                            "largo":  6
                        },
        "area_m2":  2.4000000000000004,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  25,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.084724532307709,
        "lng":  -77.0343491435051,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.4,
                            "largo":  6
                        },
        "area_m2":  2.4000000000000004,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  26,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.084567166132436,
        "lng":  -77.03451812267305,
        "icono":  "flecha_arriba",
        "region":  "Lima Oeste",
        "nombre":  "Flecha recto",
        "precio":  4350,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.66,
                            "largo":  2
                        },
        "area_m2":  1.32,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  27,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.084569788902797,
        "lng":  -77.03460127115251,
        "icono":  "flecha_arriba_izq",
        "region":  "Lima Oeste",
        "nombre":  "Recto y derecha",
        "precio":  4250,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  null,
                            "largo":  null
                        },
        "area_m2":  null,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  28,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.08551923007909,
        "lng":  -77.03439742326738,
        "icono":  "flecha_arriba",
        "region":  "Lima Oeste",
        "nombre":  "Flecha recto",
        "precio":  4350,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  null,
                            "largo":  null
                        },
        "area_m2":  null,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  29,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.08475338276313,
        "lng":  -77.03428477048875,
        "icono":  "flecha_arriba_der",
        "region":  "Lima Oeste",
        "nombre":  "Recto y derecha",
        "precio":  4250,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.9,
                            "largo":  2.8
                        },
        "area_m2":  2.52,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  30,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083601984899941,
        "lng":  -77.03470319509506,
        "icono":  "enrejado",
        "region":  "Lima Oeste",
        "nombre":  "Enrejado amarillo",
        "precio":  5700,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  6,
                            "largo":  17
                        },
        "area_m2":  102,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  31,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083565265979978,
        "lng":  -77.03452080488206,
        "icono":  "enrejado",
        "region":  "Lima Oeste",
        "nombre":  "Enrejado amarillo",
        "precio":  5700,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  6,
                            "largo":  17
                        },
        "area_m2":  102,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  32,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083465600314657,
        "lng":  -77.03471928834917,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  5,
                            "largo":  6
                        },
        "area_m2":  30,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  33,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083431504157486,
        "lng":  -77.0345476269722,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  5,
                            "largo":  6
                        },
        "area_m2":  30,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  34,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083688536619931,
        "lng":  -77.03469514846803,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  5,
                            "largo":  6
                        },
        "area_m2":  30,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  35,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083664931608151,
        "lng":  -77.03447788953783,
        "icono":  "crucero",
        "region":  "Lima Oeste",
        "nombre":  "Crucero",
        "precio":  5650,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  5,
                            "largo":  6
                        },
        "area_m2":  30,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  36,
        "tipo":  "Marca",
        "estado":  "antigua",
        "estado_fisico":  "deteriorada",
        "zona":  "Lince",
        "lat":  -12.083368557394355,
        "lng":  -77.03475683927537,
        "icono":  "flecha_arriba_izq",
        "region":  "Lima Oeste",
        "nombre":  "Recto y izquierda",
        "precio":  5300,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  1.2,
                            "largo":  4.5
                        },
        "area_m2":  5.3999999999999995,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  37,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083355443483512,
        "lng":  -77.03468978405,
        "icono":  "flecha_arriba",
        "region":  "Lima Oeste",
        "nombre":  "Flecha recto",
        "precio":  4350,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.66,
                            "largo":  2
                        },
        "area_m2":  1.32,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  38,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.084800592592574,
        "lng":  -77.03437864780427,
        "icono":  "flecha_arriba",
        "region":  "Lima Oeste",
        "nombre":  "Flecha recto",
        "precio":  4350,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.3,
                            "largo":  2
                        },
        "area_m2":  0.6,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  39,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.08469568184917,
        "lng":  -77.03454226255418,
        "icono":  "enrejado",
        "region":  "Lima Oeste",
        "nombre":  "Enrejado amarillo",
        "precio":  5700,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  6,
                            "largo":  13
                        },
        "area_m2":  78,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  40,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.084666831387517,
        "lng":  -77.03433305025102,
        "icono":  "enrejado",
        "region":  "Lima Oeste",
        "nombre":  "Enrejado amarillo",
        "precio":  5700,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  6,
                            "largo":  13
                        },
        "area_m2":  78,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  41,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083796070536074,
        "lng":  -77.03453153371812,
        "icono":  "flecha_arriba",
        "region":  "Lima Oeste",
        "nombre":  "Flecha recto",
        "precio":  4350,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.3,
                            "largo":  2
                        },
        "area_m2":  0.6,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  42,
        "tipo":  "Marca",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083777711090029,
        "lng":  -77.03444302082062,
        "icono":  "flecha_arriba_der",
        "region":  "Lima Oeste",
        "nombre":  "Recto y derecha",
        "precio":  4250,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  0.9,
                            "largo":  2.8
                        },
        "area_m2":  2.52,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    }
];

const senalesVertical = [
    {
        "id":  101,
        "tipo":  "Reglamentaria",
        "nombre":  "R-1",
        "estado":  "nueva",
        "region":  "Lima Centro",
        "zona":  "Cercado de Lima",
        "precio":  6100,
        "lat":  -12.052,
        "lng":  -77.028,
        "icono":  "R-1",
        "fecha_colocacion":  "2024-11-01",
        "distrito":  "Cercado de Lima"
    },
    {
        "id":  102,
        "tipo":  "Preventiva",
        "nombre":  "P-10A",
        "estado":  "antigua",
        "region":  "Lima Sur",
        "zona":  "Barranco",
        "precio":  5750,
        "lat":  -12.047,
        "lng":  -77.04,
        "icono":  "P-10A",
        "fecha_colocacion":  "2024-07-18",
        "distrito":  "Barranco"
    },
    {
        "id":  103,
        "tipo":  "Informativa",
        "nombre":  "I-22",
        "estado":  "sin_senal",
        "region":  "Lima Norte",
        "zona":  "Puente Piedra",
        "precio":  6400,
        "lat":  -12.06,
        "lng":  -77.1,
        "icono":  "I-22-Servicio-de-informacion",
        "fecha_colocacion":  "2024-05-09",
        "distrito":  "Puente Piedra"
    },
    {
        "id":  104,
        "tipo":  "Preventiva",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083667554387342,
        "lng":  -77.03456103801729,
        "icono":  "P-46",
        "region":  "Lima Oeste",
        "nombre":  "P-46",
        "precio":  7500,
        "fecha_colocacion":  "2026-01-18",
        "dimensiones":  {
                            "ancho":  75,
                            "largo":  75
                        },
        "area_m2":  null,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "inversion_override":  304.99,
        "distrito":  "Lince"
    },
    {
        "id":  105,
        "tipo":  "Reglamentaria",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083691159398892,
        "lng":  -77.03452080488206,
        "icono":  "R-8",
        "region":  "Lima Oeste",
        "nombre":  "R-8",
        "precio":  11700,
        "fecha_colocacion":  "2026-01-18",
        "dimensiones":  {
                            "ancho":  90,
                            "largo":  90
                        },
        "area_m2":  null,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  106,
        "tipo":  "Reglamentaria",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.083782956646186,
        "lng":  -77.03471928834917,
        "icono":  "R-30",
        "region":  "Lima Oeste",
        "nombre":  "R-30",
        "precio":  10500,
        "fecha_colocacion":  "2026-01-18",
        "dimensiones":  {
                            "ancho":  90,
                            "largo":  90
                        },
        "area_m2":  null,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  107,
        "tipo":  "Informativa",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.084800592592574,
        "lng":  -77.03431427478792,
        "icono":  "i-6-Paradero-de-buses",
        "region":  "Lima Oeste",
        "nombre":  "Paradero de buses",
        "precio":  13350,
        "fecha_colocacion":  "2026-01-18",
        "dimensiones":  {
                            "ancho":  90,
                            "largo":  90
                        },
        "area_m2":  null,
        "lamina":  "IV",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  108,
        "tipo":  "Informativa",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.08561627221952,
        "lng":  -77.03441083431245,
        "icono":  "i-6-Paradero-de-buses",
        "region":  "Lima Oeste",
        "nombre":  "Paradero de buses",
        "precio":  13350,
        "fecha_colocacion":  "2026-01-18",
        "dimensiones":  {
                            "ancho":  180,
                            "largo":  100
                        },
        "area_m2":  null,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  "src/inspeccion/inspeccion-v-108.png",
        "distrito":  "Lince"
    },
    {
        "id":  109,
        "tipo":  "Preventiva",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.085660859137105,
        "lng":  -77.03430354595186,
        "icono":  "P-48",
        "region":  "Lima Oeste",
        "nombre":  "P-48",
        "precio":  7600,
        "fecha_colocacion":  "2026-01-18",
        "dimensiones":  {
                            "ancho":  90,
                            "largo":  90
                        },
        "area_m2":  null,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  "src/inspeccion/inspeccion-v-109.png",
        "distrito":  "Lince"
    },
    {
        "id":  110,
        "tipo":  "Reglamentaria",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.085684463972822,
        "lng":  -77.03440815210344,
        "icono":  "R-44",
        "region":  "Lima Oeste",
        "nombre":  "R-44",
        "precio":  11200,
        "fecha_colocacion":  "2026-01-18",
        "dimensiones":  {
                            "ancho":  90,
                            "largo":  90
                        },
        "area_m2":  null,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  "src/inspeccion/inspeccion-v-110.png",
        "distrito":  "Lince"
    },
    {
        "id":  111,
        "tipo":  "Reglamentaria",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.085805110878399,
        "lng":  -77.03428208827974,
        "icono":  "R-42",
        "region":  "Lima Oeste",
        "nombre":  "R-42",
        "precio":  11150,
        "fecha_colocacion":  "2026-01-18",
        "dimensiones":  {
                            "ancho":  90,
                            "largo":  90
                        },
        "area_m2":  null,
        "lamina":  "I",
        "soporte":  "si",
        "inspeccionFoto":  null,
        "distrito":  "Lince"
    },
    {
        "id":  112,
        "tipo":  "Informativa",
        "estado":  "nueva",
        "estado_fisico":  "operativa",
        "zona":  "Lince",
        "lat":  -12.086904044318239,
        "lng":  -77.03412652015687,
        "icono":  "i-6-Paradero-de-buses",
        "region":  "Lima Oeste",
        "nombre":  "Paradero de buses",
        "precio":  13350,
        "fecha_colocacion":  "2026-01-22",
        "dimensiones":  {
                            "ancho":  180,
                            "largo":  100
                        },
        "area_m2":  null,
        "lamina":  "IV",
        "soporte":  "si",
        "inspeccionFoto":  "src/inspeccion/inspeccion-v-112.png",
        "distrito":  "Lince"
    }
];

// Mobiliario vial (aun sin iconos / datos)
const senalesMobiliario = [];

// Dataset actual (inicial horizontal)
let senales = senalesHorizontal;
let modoActual = "horizontal";

// Avisos ciudadanos
let avisos = ;

// Historial de cambios de senales (creadas / editadas / eliminadas / cambios de estado)
let historialSenales = [
    {
        "id":  2,
        "ts":  "2026-01-22T14:12:23.298Z",
        "accion":  "ELIMINADA",
        "modo":  "vertical",
        "urbId":  "URB-SV-LO-LINC-0010",
        "senalId":  113,
        "tipo":  "Preventiva",
        "distrito":  "Lince",
        "region":  "Lima Oeste",
        "detalle":  "Se elimino la senal."
    },
    {
        "id":  1,
        "ts":  "2026-01-22T14:10:39.436Z",
        "accion":  "CREADA",
        "modo":  "vertical",
        "urbId":  "URB-SV-LO-LINC-0010",
        "senalId":  113,
        "tipo":  "Preventiva",
        "distrito":  "Lince",
        "region":  "Lima Oeste",
        "detalle":  "Se registro una senal."
    }
];
let historialSenalesSeq = 3;

